repos:
  # Hooks for cleaning up code and checking YAML files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace      # Removes trailing whitespace at the end of lines
      - id: end-of-file-fixer       # Ensures a blank line at the end of the file
      - id: check-yaml               # Checks YAML file syntax
      - id: check-added-large-files  # Prevents accidentally committing large files (binaries)

  #  Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff                     # Runs ruff check
        args: [ --fix ]              # Fixes issues automatically when possible
      - id: ruff-format              # Runs ruff format

  #  Mypy for static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, pydantic] # Dependencies for type checking
